import type { Metadata } from "next";
import "@/app/globals.css";

import { Inter, Manrope } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Budgeable — A Simple Financial Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        layout: {
          unsafe_disableDevelopmentModeWarnings: true,
        },
      }}
    >
      <html lang="en">
        <body className={`${inter.variable} ${manrope.variable} antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
